multitenant and live accounts
Azure/azure-dev pull request #1454
Opened 2023-01-25 08:41 UTC by vhvb1989

- wip
- revert
- wip
- wip
- tests
- tests
- no cycles

2023-01-25 17:17 UTC, azure-sdk commented
<!-- #comment-cli-pr -->
## Azure Dev CLI Install Instructions

### Install scripts

#### MacOS/Linux

> May elevate using `sudo` on some platforms and configurations

bash:
```
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454 --version '' --verbose
```

pwsh:
```
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/uninstall-azd.ps1' -OutFile uninstall-azd.ps1; ./uninstall-azd.ps1
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/install-azd.ps1' -OutFile install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454' -Version '' -Verbose
```


#### Windows

PowerShell install

```
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/uninstall-azd.ps1' > uninstall-azd.ps1; ./uninstall-azd.ps1;"
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/install-azd.ps1' > install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454' -Version '' -Verbose;"
```

MSI install
```
powershell -c "irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-windows-amd64.msi' -OutFile azd-windows-amd64.msi; msiexec /i azd-windows-amd64.msi /qn"
```

### Standalone Binary

* Linux - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-linux-amd64.tar.gz
* MacOS - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-darwin-amd64.zip
* Windows - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-windows-amd64.zip

### MSI 

* https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-windows-amd64.msi

### Container

```
docker run -it azdevcliextacr.azurecr.io/azure-dev:pr-1454
```

## Documentation

<details>
<summary>learn.microsoft.com documentation</summary>

---
title: Azure Developer CLI reference (preview)
description: This article explains the syntax and parameters for the various Azure Developer CLI Preview commands.
author: hhunter-ms
ms.author: hannahhunter
ms.date: 01/25/2023
ms.service: azure-dev-cli
ms.topic: conceptual
ms.custom: devx-track-azdevcli
---

# Azure Developer CLI reference (preview)

This article explains the syntax and parameters for the various Azure Developer CLI Preview commands.

## azd

Azure Developer CLI (`azd`) is a command-line interface for developers who build Azure solutions.

### Synopsis

To begin working with Azure Developer CLI, run the `azd up` command by supplying a sample template in an empty directory:

```azdeveloper
	azd up –-template todo-nodejs-mongo
```

You can pick a template by running `azd template list` and then supplying the repo name as a value to `--template`.

The most common next commands are:

```azdeveloper
	azd pipeline config
	azd deploy
	azd monitor --overview
```

For more information, visit the Azure Developer CLI Dev Hub: [https://aka.ms/azure-dev/devhub](https://aka.ms/azure-dev/devhub).

### Options

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
  -h, --help         Gets help for azd.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd config](#azd-config): Manage the Azure Developer CLI user configuration.
* [azd deploy](#azd-deploy): Deploy the app's code to Azure.
* [azd down](#azd-down): Delete Azure resources for an app.
* [azd env](#azd-env): Manage environments.
* [azd infra](#azd-infra): Manage Azure resources.
* [azd init](#azd-init): Initialize a new app.
* [azd login](#azd-login): Log in to Azure.
* [azd logout](#azd-logout): Log out of Azure
* [azd monitor](#azd-monitor): Monitor a deployed app.
* [azd pipeline](#azd-pipeline): Manage GitHub Actions or Azure Pipelines.
* [azd provision](#azd-provision): Provision the Azure resources for an app.
* [azd restore](#azd-restore): Restore app dependencies.
* [azd template](#azd-template): Manage templates.
* [azd up](#azd-up): Initialize the app, provision Azure resources, and deploy your project with a single command.
* [azd version](#azd-version): Print the version number of Azure Developer CLI.

## azd config

Manage the Azure Developer CLI user configuration.

### Synopsis

Manage the Azure Developer CLI user configuration, which includes your default Azure subscription and location.

Available since `azure-dev-cli_0.4.0-beta.1`.

The easiest way to configure `azd` for the first time is to run [`azd init`](#azd-init). The subscription and location you select will be stored in the `config.json` file located in the config directory. To configure `azd` anytime afterwards, you'll use [`azd config set`](#azd-config-set).

The default value of the config directory is: 
* $HOME/.azd on Linux and macOS
* %USERPROFILE%\.azd on Windows


The configuration directory can be overridden by specifying a path in the AZD_CONFIG_DIR environment variable.

### Options

```azdeveloper
  -h, --help   Gets help for config.
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd config get](#azd-config-get): Gets a configuration
* [azd config list](#azd-config-list): Lists all configuration values
* [azd config reset](#azd-config-reset): Resets configuration to default
* [azd config set](#azd-config-set): Sets a configuration
* [azd config unset](#azd-config-unset): Unsets a configuration
* [Back to top](#azd)

## azd config get

Gets a configuration

### Synopsis

Gets a configuration in the configuration path.

The default value of the config directory is:
* `$HOME/.azd` on Linux and macOS
* `%USERPROFILE%\.azd` on Windows

The configuration directory can be overridden by specifying a path in the AZD_CONFIG_DIR environment variable.

```azdeveloper
azd config get <path> [flags]
```

### Options

```azdeveloper
  -h, --help            Gets help for get.
  -o, --output string   The output format (the supported formats are json). (default "json")
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd config](#azd-config): Manage the Azure Developer CLI user configuration.
* [Back to top](#azd)

## azd config list

Lists all configuration values

### Synopsis

Lists all configuration values in the configuration path.

The default value of the config directory is:
* `$HOME/.azd` on Linux and macOS
* `%USERPROFILE%\.azd` on Windows

The configuration directory can be overridden by specifying a path in the AZD_CONFIG_DIR environment variable.

```azdeveloper
azd config list [flags]
```

### Options

```azdeveloper
  -h, --help            Gets help for list.
  -o, --output string   The output format (the supported formats are json). (default "json")
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

## [...]

2023-01-25 19:52 UTC, weikanglim commented on cli/azd/cmd/util.go
> +		azCli.SetTenantId(tenantId.(string))
I haven't dug deep enough, but overall feeling is that we're exposing too much flexibility everywhere.

Most code shouldn't need to know about how to correctly obtain a user's credential. Would it be possible to invert:

1. Somehow, `login` + `init` persists both multi-tenant and single-tenant credential. The single-tenant credential is flown and injected by default.
2. The subscription listing should ignore single-tenant and only use a multi-tenant credential.
3. The rest of cli should not need to know about which credential to use. The cred provider is available if needed, but by default this should just consume the default credentials as-is.

2023-01-25 20:17 UTC, azure-sdk commented
<!-- #comment-cli-pr -->
## Azure Dev CLI Install Instructions

### Install scripts

#### MacOS/Linux

> May elevate using `sudo` on some platforms and configurations

bash:
```
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454 --version '' --verbose
```

pwsh:
```
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/uninstall-azd.ps1' -OutFile uninstall-azd.ps1; ./uninstall-azd.ps1
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/install-azd.ps1' -OutFile install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454' -Version '' -Verbose
```


#### Windows

PowerShell install

```
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/uninstall-azd.ps1' > uninstall-azd.ps1; ./uninstall-azd.ps1;"
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/install-azd.ps1' > install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454' -Version '' -Verbose;"
```

MSI install
```
powershell -c "irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-windows-amd64.msi' -OutFile azd-windows-amd64.msi; msiexec /i azd-windows-amd64.msi /qn"
```

### Standalone Binary

* Linux - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-linux-amd64.tar.gz
* MacOS - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-darwin-amd64.zip
* Windows - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-windows-amd64.zip

### MSI 

* https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-windows-amd64.msi

### Container

```
docker run -it azdevcliextacr.azurecr.io/azure-dev:pr-1454
```

## Documentation

<details>
<summary>learn.microsoft.com documentation</summary>

---
title: Azure Developer CLI reference (preview)
description: This article explains the syntax and parameters for the various Azure Developer CLI Preview commands.
author: hhunter-ms
ms.author: hannahhunter
ms.date: 01/25/2023
ms.service: azure-dev-cli
ms.topic: conceptual
ms.custom: devx-track-azdevcli
---

# Azure Developer CLI reference (preview)

This article explains the syntax and parameters for the various Azure Developer CLI Preview commands.

## azd

Azure Developer CLI (`azd`) is a command-line interface for developers who build Azure solutions.

### Synopsis

To begin working with Azure Developer CLI, run the `azd up` command by supplying a sample template in an empty directory:

```azdeveloper
	azd up –-template todo-nodejs-mongo
```

You can pick a template by running `azd template list` and then supplying the repo name as a value to `--template`.

The most common next commands are:

```azdeveloper
	azd pipeline config
	azd deploy
	azd monitor --overview
```

For more information, visit the Azure Developer CLI Dev Hub: [https://aka.ms/azure-dev/devhub](https://aka.ms/azure-dev/devhub).

### Options

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
  -h, --help         Gets help for azd.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd config](#azd-config): Manage the Azure Developer CLI user configuration.
* [azd deploy](#azd-deploy): Deploy the app's code to Azure.
* [azd down](#azd-down): Delete Azure resources for an app.
* [azd env](#azd-env): Manage environments.
* [azd infra](#azd-infra): Manage Azure resources.
* [azd init](#azd-init): Initialize a new app.
* [azd login](#azd-login): Log in to Azure.
* [azd logout](#azd-logout): Log out of Azure
* [azd monitor](#azd-monitor): Monitor a deployed app.
* [azd pipeline](#azd-pipeline): Manage GitHub Actions or Azure Pipelines.
* [azd provision](#azd-provision): Provision the Azure resources for an app.
* [azd restore](#azd-restore): Restore app dependencies.
* [azd template](#azd-template): Manage templates.
* [azd up](#azd-up): Initialize the app, provision Azure resources, and deploy your project with a single command.
* [azd version](#azd-version): Print the version number of Azure Developer CLI.

## azd config

Manage the Azure Developer CLI user configuration.

### Synopsis

Manage the Azure Developer CLI user configuration, which includes your default Azure subscription and location.

Available since `azure-dev-cli_0.4.0-beta.1`.

The easiest way to configure `azd` for the first time is to run [`azd init`](#azd-init). The subscription and location you select will be stored in the `config.json` file located in the config directory. To configure `azd` anytime afterwards, you'll use [`azd config set`](#azd-config-set).

The default value of the config directory is: 
* $HOME/.azd on Linux and macOS
* %USERPROFILE%\.azd on Windows


The configuration directory can be overridden by specifying a path in the AZD_CONFIG_DIR environment variable.

### Options

```azdeveloper
  -h, --help   Gets help for config.
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd config get](#azd-config-get): Gets a configuration
* [azd config list](#azd-config-list): Lists all configuration values
* [azd config reset](#azd-config-reset): Resets configuration to default
* [azd config set](#azd-config-set): Sets a configuration
* [azd config unset](#azd-config-unset): Unsets a configuration
* [Back to top](#azd)

## azd config get

Gets a configuration

### Synopsis

Gets a configuration in the configuration path.

The default value of the config directory is:
* `$HOME/.azd` on Linux and macOS
* `%USERPROFILE%\.azd` on Windows

The configuration directory can be overridden by specifying a path in the AZD_CONFIG_DIR environment variable.

```azdeveloper
azd config get <path> [flags]
```

### Options

```azdeveloper
  -h, --help            Gets help for get.
  -o, --output string   The output format (the supported formats are json). (default "json")
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd config](#azd-config): Manage the Azure Developer CLI user configuration.
* [Back to top](#azd)

## azd config list

Lists all configuration values

### Synopsis

Lists all configuration values in the configuration path.

The default value of the config directory is:
* `$HOME/.azd` on Linux and macOS
* `%USERPROFILE%\.azd` on Windows

The configuration directory can be overridden by specifying a path in the AZD_CONFIG_DIR environment variable.

```azdeveloper
azd config list [flags]
```

### Options

```azdeveloper
  -h, --help            Gets help for list.
  -o, --output string   The output format (the supported formats are json). (default "json")
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

## [...]

2023-01-25 20:33 UTC, wbreza requested changes
The current PR introduces additional complexity to a few different areas of `azd`.

1. Showing all subscriptions across all tenants
  - We don't have a good UX experience to show/group subs by tenant
  - Performance impact for query for all subs across all tenants
  
2. Introduce complexity to now add a token/credential provider to many flows vs a single credential 

**Recommendation**:
1. Support `--tenant-id` on `azd login` command for users who know their tenant Id up front and their account has access to multiple tenants
2. After running `azd login` if your account has access to multiple tenants, show a prompt to the user to have them select the tenant id that `azd` will use for future commands

**Other suggestions:**
1. If we want to support easier switching across tenants we could also introduce new commands like:
  - `azd tenant list`
  - `azd tenant set <TENANT_ID>

2023-01-31 23:56 UTC, azure-sdk commented
<!-- #comment-cli-pr -->
## Azure Dev CLI Install Instructions

### Install scripts

#### MacOS/Linux

> May elevate using `sudo` on some platforms and configurations

bash:
```
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454 --version '' --verbose
```

pwsh:
```
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/uninstall-azd.ps1' -OutFile uninstall-azd.ps1; ./uninstall-azd.ps1
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/install-azd.ps1' -OutFile install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454' -Version '' -Verbose
```


#### Windows

PowerShell install

```
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/uninstall-azd.ps1' > uninstall-azd.ps1; ./uninstall-azd.ps1;"
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/install-azd.ps1' > install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454' -Version '' -Verbose;"
```

MSI install
```
powershell -c "irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-windows-amd64.msi' -OutFile azd-windows-amd64.msi; msiexec /i azd-windows-amd64.msi /qn"
```

### Standalone Binary

* Linux - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-linux-amd64.tar.gz
* MacOS - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-darwin-amd64.zip
* Windows - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-windows-amd64.zip

### MSI 

* https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1454/azd-windows-amd64.msi

### Container

```
docker run -it azdevcliextacr.azurecr.io/azure-dev:pr-1454
```

## Documentation

<details>
<summary>learn.microsoft.com documentation</summary>

---
title: Azure Developer CLI reference (preview)
description: This article explains the syntax and parameters for the various Azure Developer CLI Preview commands.
author: hhunter-ms
ms.author: hannahhunter
ms.date: 01/31/2023
ms.service: azure-dev-cli
ms.topic: conceptual
ms.custom: devx-track-azdevcli
---

# Azure Developer CLI reference (preview)

This article explains the syntax and parameters for the various Azure Developer CLI Preview commands.

## azd

Azure Developer CLI (`azd`) is a command-line interface for developers who build Azure solutions.

### Synopsis

To begin working with Azure Developer CLI, run the `azd up` command by supplying a sample template in an empty directory:

```azdeveloper
	azd up –-template todo-nodejs-mongo
```

You can pick a template by running `azd template list` and then supplying the repo name as a value to `--template`.

The most common next commands are:

```azdeveloper
	azd pipeline config
	azd deploy
	azd monitor --overview
```

For more information, visit the Azure Developer CLI Dev Hub: [https://aka.ms/azure-dev/devhub](https://aka.ms/azure-dev/devhub).

### Options

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
  -h, --help         Gets help for azd.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd config](#azd-config): Manage the Azure Developer CLI user configuration.
* [azd deploy](#azd-deploy): Deploy the app's code to Azure.
* [azd down](#azd-down): Delete Azure resources for an app.
* [azd env](#azd-env): Manage environments.
* [azd infra](#azd-infra): Manage Azure resources.
* [azd init](#azd-init): Initialize a new app.
* [azd login](#azd-login): Log in to Azure.
* [azd logout](#azd-logout): Log out of Azure
* [azd monitor](#azd-monitor): Monitor a deployed app.
* [azd pipeline](#azd-pipeline): Manage GitHub Actions or Azure Pipelines.
* [azd provision](#azd-provision): Provision the Azure resources for an app.
* [azd restore](#azd-restore): Restore app dependencies.
* [azd template](#azd-template): Manage templates.
* [azd up](#azd-up): Initialize the app, provision Azure resources, and deploy your project with a single command.
* [azd version](#azd-version): Print the version number of Azure Developer CLI.

## azd config

Manage the Azure Developer CLI user configuration.

### Synopsis

Manage the Azure Developer CLI user configuration, which includes your default Azure subscription and location.

Available since `azure-dev-cli_0.4.0-beta.1`.

The easiest way to configure `azd` for the first time is to run [`azd init`](#azd-init). The subscription and location you select will be stored in the `config.json` file located in the config directory. To configure `azd` anytime afterwards, you'll use [`azd config set`](#azd-config-set).

The default value of the config directory is: 
* $HOME/.azd on Linux and macOS
* %USERPROFILE%\.azd on Windows


The configuration directory can be overridden by specifying a path in the AZD_CONFIG_DIR environment variable.

### Options

```azdeveloper
  -h, --help   Gets help for config.
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd config get](#azd-config-get): Gets a configuration
* [azd config list](#azd-config-list): Lists all configuration values
* [azd config reset](#azd-config-reset): Resets configuration to default
* [azd config set](#azd-config-set): Sets a configuration
* [azd config unset](#azd-config-unset): Unsets a configuration
* [Back to top](#azd)

## azd config get

Gets a configuration

### Synopsis

Gets a configuration in the configuration path.

The default value of the config directory is:
* `$HOME/.azd` on Linux and macOS
* `%USERPROFILE%\.azd` on Windows

The configuration directory can be overridden by specifying a path in the AZD_CONFIG_DIR environment variable.

```azdeveloper
azd config get <path> [flags]
```

### Options

```azdeveloper
  -h, --help            Gets help for get.
  -o, --output string   The output format (the supported formats are json). (default "json")
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd config](#azd-config): Manage the Azure Developer CLI user configuration.
* [Back to top](#azd)

## azd config list

Lists all configuration values

### Synopsis

Lists all configuration values in the configuration path.

The default value of the config directory is:
* `$HOME/.azd` on Linux and macOS
* `%USERPROFILE%\.azd` on Windows

The configuration directory can be overridden by specifying a path in the AZD_CONFIG_DIR environment variable.

```azdeveloper
azd config list [flags]
```

### Options

```azdeveloper
  -h, --help            Gets help for list.
  -o, --output string   The output format (the supported formats are json). (default "json")
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

## [...]

2023-02-02 19:23 UTC, vhvb1989 commented
Closing in favor of: https://github.com/Azure/azure-dev/pull/1478

2023-02-02 19:23 UTC, closed without merging