Create an `alpha` version of `azure.yaml` schema
Azure/azure-dev pull request #2251
Opened 2023-05-17 19:06 UTC by ellismg

We don't want to include any values in the schema that are tied to alpha features in the `v1.0` schema, since we may remove or change these values during development.

This change introduces a new copy of this schema and adds "terraform" as a supported member of an enum (this is a new value that is supported behind an alpha feature)

Fixes #1925

2023-05-17 20:56 UTC, rajeshkamal5050 requested changes

2023-05-17 20:56 UTC, rajeshkamal5050 commented on schemas/alpha/azure.yaml.json
> +                            "aks"
Can you also add springapp?

2023-05-17 23:02 UTC, ellismg commented
/check-enforcer override

2023-05-17 23:06 UTC, savannahostrowski commented
Should we also update the TF todo templates with the alpha schema as part of this PR?

2023-05-18 00:05 UTC, ellismg commented
Pushed [3aaaa3c](https://github.com/Azure/azure-dev/pull/2251/commits/3aaaa3c8c4c0e1e47fcbfe4c6e5e797269332306) to reference these in the bicep templates, @savannahostrowski.

2023-05-18 00:06 UTC, savannahostrowski approved these changes
LGTM! We should also probably let the ASA team know to update their template as well!

cc:@rajeshkamal5050

2023-05-18 00:07 UTC, azure-sdk commented
<!-- #comment-repoman-generate -->
## Repoman Generation Results
Repoman pushed changes to remotes for the following projects:
### Project: **azd-starter-terraform**
#### Remote: **azure-samples-staging**
##### Branch: **pr/2251**

You can initialize this project with:
```bash
azd init -t Azure-Samples/azd-starter-terraform -b pr/2251
```

[View Changes](https://github.com/Azure-Samples/azd-starter-terraform/tree/pr/2251) | [Compare Changes](https://github.com/Azure-Samples/azd-starter-terraform/compare/staging...pr/2251)

---
### Project: **todo-java-postgresql-terraform**
#### Remote: **azure-samples-staging**
##### Branch: **pr/2251**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-java-postgresql-terraform -b pr/2251
```

[View Changes](https://github.com/Azure-Samples/todo-java-postgresql-terraform/tree/pr/2251) | [Compare Changes](https://github.com/Azure-Samples/todo-java-postgresql-terraform/compare/staging...pr/2251)

---
### Project: **todo-nodejs-mongo-terraform**
#### Remote: **azure-samples-staging**
##### Branch: **pr/2251**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-terraform -b pr/2251
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-terraform/tree/pr/2251) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-terraform/compare/staging...pr/2251)

---
### Project: **todo-python-mongo-terraform**
#### Remote: **azure-samples-staging**
##### Branch: **pr/2251**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-terraform -b pr/2251
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-terraform/tree/pr/2251) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-terraform/compare/staging...pr/2251)

---

2023-05-18 00:36 UTC, rajeshkamal5050 approved these changes

2023-05-18 00:44 UTC, azure-sdk commented
<!-- #comment-cli-pr -->
## Azure Dev CLI Install Instructions

### Install scripts

#### MacOS/Linux

> May elevate using `sudo` on some platforms and configurations

bash:
```
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251 --version '' --verbose --skip-verify
```

pwsh:
```
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/uninstall-azd.ps1' -OutFile uninstall-azd.ps1; ./uninstall-azd.ps1
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/install-azd.ps1' -OutFile install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251' -Version '' -SkipVerify -Verbose
```


#### Windows

PowerShell install

```
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/uninstall-azd.ps1' > uninstall-azd.ps1; ./uninstall-azd.ps1;"
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/install-azd.ps1' > install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251' -Version '' -SkipVerify -Verbose;"
```

MSI install
```
powershell -c "irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/azd-windows-amd64.msi' -OutFile azd-windows-amd64.msi; msiexec /i azd-windows-amd64.msi /qn"
```

### Standalone Binary

* Linux - 
    * x86_64 - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/azd-linux-amd64.tar.gz
    * ARM64 - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/azd-linux-arm64.tar.gz
* MacOS - 
    * x86_64 - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/azd-darwin-amd64.zip
    * ARM64 - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/azd-darwin-arm64.zip
* Windows - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/azd-windows-amd64.zip

### MSI

* https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/2251/azd-windows-amd64.msi

### Container

```
docker run -it azdevcliextacr.azurecr.io/azure-dev:pr-2251
```

## Documentation

<details>
<summary>learn.microsoft.com documentation</summary>

---
title: Azure Developer CLI reference (preview)
description: This article explains the syntax and parameters for the various Azure Developer CLI Preview commands.
author: alexwolfmsft
ms.author: alexwolf
ms.date: 05/18/2023
ms.service: azure-dev-cli
ms.topic: conceptual
ms.custom: devx-track-azdevcli
---

# Azure Developer CLI reference (preview)

This article explains the syntax and parameters for the various Azure Developer CLI Preview commands.

## azd

The Azure Developer CLI (`azd`) is an open-source tool that helps onboard and manage your application on Azure

### Options

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
  -h, --help         Gets help for azd.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd auth](#azd-auth): Authenticate with Azure.
* [azd config](#azd-config): Manage azd configurations (ex: default Azure subscription, location).
* [azd deploy](#azd-deploy): Deploy the application's code to Azure.
* [azd down](#azd-down): Delete Azure resources for an application.
* [azd env](#azd-env): Manage environments.
* [azd init](#azd-init): Initialize a new application.
* [azd monitor](#azd-monitor): Monitor a deployed application. (Beta)
* [azd package](#azd-package): Packages the application's code to be deployed to Azure. (Beta)
* [azd pipeline](#azd-pipeline): Manage and configure your deployment pipelines. (Beta)
* [azd provision](#azd-provision): Provision the Azure resources for an application.
* [azd restore](#azd-restore): Restores the application's dependencies. (Beta)
* [azd template](#azd-template): Find and view template details. (Beta)
* [azd up](#azd-up): Provision Azure resources, and deploy your project with a single command.
* [azd version](#azd-version): Print the version number of Azure Developer CLI.

## azd auth

Authenticate with Azure.

### Options

```azdeveloper
  -h, --help   Gets help for auth.
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd auth login](#azd-auth-login): Log in to Azure.
* [azd auth logout](#azd-auth-logout): Log out of Azure.
* [Back to top](#azd)

## azd auth login

Log in to Azure.

### Synopsis

Log in to Azure.

When run without any arguments, log in interactively using a browser. To log in using a device code, pass
--use-device-code.

To log in as a service principal, pass --client-id and --tenant-id as well as one of: --client-secret, 
--client-certificate, or --federated-credential-provider.


```azdeveloper
azd auth login [flags]
```

### Options

```azdeveloper
      --check-status                           Checks the log-in status instead of logging in.
      --client-certificate string              The path to the client certificate for the service principal to authenticate with.
      --client-id string                       The client id for the service principal to authenticate with.
      --client-secret string                   The client secret for the service principal to authenticate with. Set to the empty string to read the value from the console.
      --federated-credential-provider string   The provider to use to acquire a federated token to authenticate with.
  -h, --help                                   Gets help for login.
      --redirect-port int                      Choose the port to be used as part of the redirect URI during interactive login.
      --tenant-id string                       The tenant id or domain name to authenticate with.
      --use-device-code[=true]                 When true, log in by using a device code instead of a browser.
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd auth](#azd-auth): Authenticate with Azure.
* [Back to top](#azd)

## azd auth logout

Log out of Azure.

### Synopsis

Log out of Azure

```azdeveloper
azd auth logout [flags]
```

### Options

```azdeveloper
  -h, --help   Gets help for logout.
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd auth](#azd-auth): Authenticate with Azure.
* [Back to top](#azd)

## azd config

Manage azd configurations (ex: default Azure subscription, location).

### Synopsis

Manage the Azure Developer CLI user configuration, which includes your default Azure subscription and location.

Available since `azure-dev-cli_0.4.0-beta.1`.

The easiest way to configure `azd` for the first time is to run [`azd init`](#azd-init). The subscription and location you select will be stored in the `config.json` file located in the config directory. To configure `azd` anytim [...]

2023-05-18 01:17 UTC, merged