fix bug on dotnet target port for empty result or message after config
Azure/azure-dev pull request #3660
Opened 2024-04-06 00:17 UTC by hemarina

fix #3657

2024-04-06 01:06 UTC, azure-sdk commented
<!-- #comment-cli-pr -->
## Azure Dev CLI Install Instructions

### Install scripts

#### MacOS/Linux

> May elevate using `sudo` on some platforms and configurations

bash:
```
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660 --version '' --verbose --skip-verify
```

pwsh:
```
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/uninstall-azd.ps1' -OutFile uninstall-azd.ps1; ./uninstall-azd.ps1
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/install-azd.ps1' -OutFile install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660' -Version '' -SkipVerify -Verbose
```


#### Windows

PowerShell install

```
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/uninstall-azd.ps1' > uninstall-azd.ps1; ./uninstall-azd.ps1;"
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/install-azd.ps1' > install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660' -Version '' -SkipVerify -Verbose;"
```

MSI install
```
powershell -c "irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/azd-windows-amd64.msi' -OutFile azd-windows-amd64.msi; msiexec /i azd-windows-amd64.msi /qn"
```

### Standalone Binary

* Linux - 
    * x86_64 - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/azd-linux-amd64.tar.gz
    * ARM64 - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/azd-linux-arm64.tar.gz
* MacOS - 
    * x86_64 - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/azd-darwin-amd64.zip
    * ARM64 - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/azd-darwin-arm64.zip
* Windows - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/azd-windows-amd64.zip

### MSI

* https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3660/azd-windows-amd64.msi

## Documentation

<details>
<summary>learn.microsoft.com documentation</summary>

---
title: Azure Developer CLI reference
description: This article explains the syntax and parameters for the various Azure Developer CLI commands.
author: alexwolfmsft
ms.author: alexwolf
ms.date: 04/06/2024
ms.service: azure-dev-cli
ms.topic: conceptual
ms.custom: devx-track-azdevcli
---

# Azure Developer CLI reference

This article explains the syntax and parameters for the various Azure Developer CLI commands.

## azd

The Azure Developer CLI (`azd`) is an open-source tool that helps onboard and manage your application on Azure

### Options

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --docs         Opens the documentation for azd in your web browser.
  -h, --help         Gets help for azd.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd auth](#azd-auth): Authenticate with Azure.
* [azd config](#azd-config): Manage azd configurations (ex: default Azure subscription, location).
* [azd deploy](#azd-deploy): Deploy the application's code to Azure.
* [azd down](#azd-down): Delete Azure resources for an application.
* [azd env](#azd-env): Manage environments.
* [azd hooks](#azd-hooks): Develop, test and run hooks for an application. (Beta)
* [azd init](#azd-init): Initialize a new application.
* [azd monitor](#azd-monitor): Monitor a deployed application. (Beta)
* [azd package](#azd-package): Packages the application's code to be deployed to Azure. (Beta)
* [azd pipeline](#azd-pipeline): Manage and configure your deployment pipelines. (Beta)
* [azd provision](#azd-provision): Provision the Azure resources for an application.
* [azd restore](#azd-restore): Restores the application's dependencies. (Beta)
* [azd show](#azd-show): Display information about your app and its resources.
* [azd template](#azd-template): Find and view template details. (Beta)
* [azd up](#azd-up): Provision Azure resources, and deploy your project with a single command.
* [azd version](#azd-version): Print the version number of Azure Developer CLI.

## azd auth

Authenticate with Azure.

### Options

```azdeveloper
      --docs   Opens the documentation for azd auth in your web browser.
  -h, --help   Gets help for auth.
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd auth login](#azd-auth-login): Log in to Azure.
* [azd auth logout](#azd-auth-logout): Log out of Azure.
* [Back to top](#azd)

## azd auth login

Log in to Azure.

### Synopsis

Log in to Azure.

When run without any arguments, log in interactively using a browser. To log in using a device code, pass
--use-device-code.

To log in as a service principal, pass --client-id and --tenant-id as well as one of: --client-secret,
--client-certificate, or --federated-credential-provider.


```azdeveloper
azd auth login [flags]
```

### Options

```azdeveloper
      --check-status                           Checks the log-in status instead of logging in.
      --client-certificate string              The path to the client certificate for the service principal to authenticate with.
      --client-id string                       The client id for the service principal to authenticate with.
      --client-secret string                   The client secret for the service principal to authenticate with. Set to the empty string to read the value from the console.
      --docs                                   Opens the documentation for azd auth login in your web browser.
      --federated-credential-provider string   The provider to use to acquire a federated token to authenticate with.
  -h, --help                                   Gets help for login.
      --redirect-port int                      Choose the port to be used as part of the redirect URI during interactive login.
      --tenant-id string                       The tenant id or domain name to authenticate with.
      --use-device-code[=true]                 When true, log in by using a device code instead of a browser.
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd auth](#azd-auth): Authenticate with Azure.
* [Back to top](#azd)

## azd auth logout

Log out of Azure.

### Synopsis

Log out of Azure

```azdeveloper
azd auth logout [flags]
```

### Options

```azdeveloper
      --docs   Opens the documentation for azd auth logout in your web browser.
  -h, --help   Gets help for logout.
```

### Options inherited from parent commands

```azdeveloper
  -C, --cwd string   Sets the current working directory.
      --debug        Enables debugging and diagnostics logging.
      --no-prompt    Accepts the default value instead of prompting, or it fails if there is no default.
```

### See also

* [azd auth](#azd-auth): Authenticate with Azure.
* [Back to top](#azd)

## azd config

Manage azd configurations (ex: default Azure subscription, location).

### Synopsis

Manage the [...]

2024-04-06 04:32 UTC, vhvb1989 approved these changes

2024-04-08 16:35 UTC, rajeshkamal5050 requested changes
Don't think this is a blocker for 1.8.0. Let's merge after tomorrows release.

2024-04-12 18:51 UTC, rajeshkamal5050 commented on cli/azd/pkg/tools/dotnet/dotnet.go
> +			Suggestion: fmt.Sprintf("project '%s' isn't enabled for container support. To enable SDK "+
`EnableSdkContainerSupport ` Could be one of the reasons for an empty dotnet config? Should we also surface the error from the dotnet command too?

2024-04-12 18:51 UTC, rajeshkamal5050 approved these changes

2024-04-18 23:53 UTC, merged