Change golangci-lint feature to an updated features repo
Azure/azure-dev pull request #4506
Opened 2024-10-31 16:49 UTC by PabloZaiden

The old repo used for the golangci-lint feature is abandoned and a new working release was created in a new repo.
The current release properly supports ARM-based computers.

This PR Fixes #4505

2024-10-31 17:54 UTC, weikanglim submitted a review, later dismissed
Hi @PabloZaiden thank you for your contribution!

Can you reference any existing artifacts (issues, discussions, PRs) that describes how ownership is being transferred from https://github.com/guiyomh/features to https://github.com/PabloZaiden/devcontainers-features, since it is a fork? From the changeset [here](https://github.com/guiyomh/features/compare/main...PabloZaiden:devcontainers-features:main), it looks like the changes made are largely just around release management.

Correct if me if I'm wrong, but the arm64 feature support was actually done as part of https://github.com/guiyomh/features/pull/37?

Based on this initial look, I'm going to wait on understanding more about what conversations has been had with the original author guiyomh in the strategy here before providing an approval. Thanks!

2024-10-31 18:05 UTC, PabloZaiden commented
@weikanglim I've contacted the owner of the original repo to ask him to generate new releases since, after that fix (and several other too), they never generated new releases for the devcontainer features.

I'd gladly revert it back to the original repo if it's being regularly updated, but even when the last commit was from 11-30-2023, the last build used by the devcontainers is from mid 2022.

Until that is properly fixed, this issue is blocking development on ARM based computers.

2024-11-01 16:52 UTC, PabloZaiden commented
One of the checks in the pipeline seems to be stuck? It appears as "pending", but the actual jobs were successful

2024-11-01 22:07 UTC, vhvb1989 requested changes
Let's not use forks.
I'd rather move the feature out of the devcontainer and use the docs for telling folks to manually install the golangci-lint.

2024-11-03 12:54 UTC, PabloZaiden commented
The contributing guide already points to the installation guide for golangci-lint. Would you rather go the path of closing this PR and opening a new one that just removes the outdated dev container feature then?

2024-11-04 20:30 UTC, PabloZaiden commented
@vhvb1989 I've just realized that the `ghcr.io/devcontainers/features/go:1` feature already includes `golangci-lint` and it works on ARM based Macs out of the box.

I've updated the PR with the extra `golangci-lint` feature removed.

2024-11-04 21:01 UTC, vhvb1989 approved these changes

2024-11-04 21:01 UTC, vhvb1989 commented
/check-enforcer override

2024-11-04 21:02 UTC, merged

2024-11-04 21:02 UTC, vhvb1989 commented
Thank you @PabloZaiden !