Make .devcontainer language specific
Azure/azure-dev pull request #471
Opened 2022-08-15 19:36 UTC by savannahostrowski

Closes #88 

There was a comment on this issue about deleting the reference to common/.devcontainer from repo.yaml but I don't see that in the file. Let me know if I missed anything!

2022-08-15 19:44 UTC, azure-sdk commented
<!-- #comment-repoman-generate -->
## Repoman Generation Results
Repoman pushed changes to remotes for the following projects:
### Project: **todo-csharp-cosmos-sql**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-cosmos-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/compare/main...pr/471)

---
### Project: **todo-csharp-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-mongo/compare/main...pr/471)

---
### Project: **todo-csharp-sql**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-sql/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo-aca**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo-swa-func**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/compare/main...pr/471)

---
### Project: **todo-python-mongo-aca**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/compare/main...pr/471)

---
### Project: **todo-python-mongo-swa-func**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/compare/main...pr/471)

---
### Project: **todo-python-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo/compare/main...pr/471)

---

2022-08-16 17:14 UTC, jongio requested changes

2022-08-16 17:14 UTC, jongio commented on templates/todo/projects/csharp-mongo/.devcontainer/Dockerfile
> +ARG VARIANT=bullseye
Seems like this is still the same for all templates.  We could keep it in common.

2022-08-16 17:14 UTC, jongio commented on templates/todo/projects/python-mongo-aca/.devcontainer/devcontainer.json
> +{
Some of these devcontainer.json files are the same.  We can re-arrange how we store them in common and then copy any that are the same out to the various templates.

2022-08-17 20:44 UTC, azure-sdk commented
<!-- #comment-repoman-generate -->
## Repoman Generation Results
Repoman pushed changes to remotes for the following projects:
### Project: **todo-csharp-cosmos-sql**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-cosmos-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/compare/main...pr/471)

---
### Project: **todo-csharp-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-mongo/compare/main...pr/471)

---
### Project: **todo-csharp-sql**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-sql/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo-aca**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo-swa-func**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/compare/main...pr/471)

---
### Project: **todo-python-mongo-aca**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/compare/main...pr/471)

---
### Project: **todo-python-mongo-swa-func**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/compare/main...pr/471)

---
### Project: **todo-python-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo/compare/main...pr/471)

---

2022-08-17 20:47 UTC, jongio commented on templates/todo/projects/csharp-mongo/.devcontainer/Dockerfile
> +ARG VARIANT=bullseye
Fixed in my commit

2022-08-17 20:47 UTC, jongio commented on templates/todo/projects/python-mongo-aca/.devcontainer/devcontainer.json
> +{
Fixed in my commit

2022-08-17 20:48 UTC, azure-sdk commented
<!-- #comment-repoman-generate -->
## Repoman Generation Results
Repoman pushed changes to remotes for the following projects:
### Project: **todo-csharp-cosmos-sql**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-cosmos-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/compare/main...pr/471)

---
### Project: **todo-csharp-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-mongo/compare/main...pr/471)

---
### Project: **todo-csharp-sql**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-sql/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo-aca**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo-swa-func**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/compare/main...pr/471)

---
### Project: **todo-python-mongo-aca**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/compare/main...pr/471)

---
### Project: **todo-python-mongo-swa-func**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/compare/main...pr/471)

---
### Project: **todo-python-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo/compare/main...pr/471)

---

2022-08-17 20:49 UTC, jongio approved these changes

2022-08-17 21:08 UTC, azure-sdk commented
<!-- #comment-repoman-generate -->
## Repoman Generation Results
Repoman pushed changes to remotes for the following projects:
### Project: **todo-csharp-cosmos-sql**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-cosmos-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/compare/main...pr/471)

---
### Project: **todo-csharp-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-mongo/compare/main...pr/471)

---
### Project: **todo-csharp-sql**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-sql/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo-aca**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo-swa-func**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/compare/main...pr/471)

---
### Project: **todo-python-mongo-aca**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/compare/main...pr/471)

---
### Project: **todo-python-mongo-swa-func**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/compare/main...pr/471)

---
### Project: **todo-python-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo/compare/main...pr/471)

---

2022-08-17 21:12 UTC, jongio commented
Marking as draft so we can do a manual test pass against all of these templates with the new devcontainer updates.

2022-08-17 21:12 UTC, azure-sdk commented
<!-- #comment-repoman-generate -->
## Repoman Generation Results
Repoman pushed changes to remotes for the following projects:
### Project: **todo-csharp-cosmos-sql**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-cosmos-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/compare/main...pr/471)

---
### Project: **todo-csharp-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-mongo/compare/main...pr/471)

---
### Project: **todo-csharp-sql**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-sql/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo-aca**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo-swa-func**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/compare/main...pr/471)

---
### Project: **todo-nodejs-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/compare/main...pr/471)

---
### Project: **todo-python-mongo-aca**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/compare/main...pr/471)

---
### Project: **todo-python-mongo-swa-func**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/compare/main...pr/471)

---
### Project: **todo-python-mongo**
#### Remote: **azure-samples**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo/compare/main...pr/471)

---

2022-08-17 22:22 UTC, vhvb1989 approved these changes
It would be good to have CI/CD tests to validate the Dockerfile (can build OK) and devcontainer is valid

2022-08-17 22:22 UTC, vhvb1989 commented on templates/common/.devcontainer/Dockerfile/base/Dockerfile
> +RUN curl -fsSL https://aka.ms/install-azd.sh | bash
```suggestion
RUN curl -fsSL https://aka.ms/install-azd.sh | bash

```

2022-08-23 15:21 UTC, azure-sdk commented
<!-- #comment-repoman-generate -->
## Repoman Generation Results
Repoman pushed changes to remotes for the following projects:
### Project: **todo-csharp-cosmos-sql**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-cosmos-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/compare/staging...pr/471)

---
### Project: **todo-csharp-mongo**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-mongo/compare/staging...pr/471)

---
### Project: **todo-csharp-sql**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-sql/compare/staging...pr/471)

---
### Project: **todo-nodejs-mongo-aca**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/compare/staging...pr/471)

---
### Project: **todo-nodejs-mongo-swa-func**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/compare/staging...pr/471)

---
### Project: **todo-nodejs-mongo**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/compare/staging...pr/471)

---
### Project: **todo-python-mongo-aca**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/compare/staging...pr/471)

---
### Project: **todo-python-mongo-swa-func**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/compare/staging...pr/471)

---
### Project: **todo-python-mongo**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo/compare/staging...pr/471)

---

2022-08-23 15:23 UTC, jongio commented
> It would be good to have CI/CD tests to validate the Dockerfile (can build OK) and devcontainer is valid

It is now possible https://github.com/Azure/azure-dev/issues/504

2022-08-23 15:26 UTC, azure-sdk commented
<!-- #comment-repoman-generate -->
## Repoman Generation Results
Repoman pushed changes to remotes for the following projects:
### Project: **todo-csharp-cosmos-sql**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-cosmos-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/compare/staging...pr/471)

---
### Project: **todo-csharp-mongo**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-mongo/compare/staging...pr/471)

---
### Project: **todo-csharp-sql**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-sql/compare/staging...pr/471)

---
### Project: **todo-nodejs-mongo-aca**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/compare/staging...pr/471)

---
### Project: **todo-nodejs-mongo-swa-func**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/compare/staging...pr/471)

---
### Project: **todo-nodejs-mongo**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/compare/staging...pr/471)

---
### Project: **todo-python-mongo-aca**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/compare/staging...pr/471)

---
### Project: **todo-python-mongo-swa-func**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/compare/staging...pr/471)

---
### Project: **todo-python-mongo**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo/compare/staging...pr/471)

---

2022-08-23 15:32 UTC, azure-sdk commented
<!-- #comment-repoman-generate -->
## Repoman Generation Results
Repoman pushed changes to remotes for the following projects:
### Project: **todo-csharp-cosmos-sql**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-cosmos-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/compare/staging...pr/471)

---
### Project: **todo-csharp-mongo**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-mongo/compare/staging...pr/471)

---
### Project: **todo-csharp-sql**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-csharp-sql -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-csharp-sql/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-csharp-sql/compare/staging...pr/471)

---
### Project: **todo-nodejs-mongo-aca**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/compare/staging...pr/471)

---
### Project: **todo-nodejs-mongo-swa-func**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/compare/staging...pr/471)

---
### Project: **todo-nodejs-mongo**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-nodejs-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-nodejs-mongo/compare/staging...pr/471)

---
### Project: **todo-python-mongo-aca**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-aca -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-aca/compare/staging...pr/471)

---
### Project: **todo-python-mongo-swa-func**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo-swa-func -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo-swa-func/compare/staging...pr/471)

---
### Project: **todo-python-mongo**
#### Remote: **azure-samples-staging**
##### Branch: **pr/471**

You can initialize this project with:
```bash
azd init -t Azure-Samples/todo-python-mongo -b pr/471
```

[View Changes](https://github.com/Azure-Samples/todo-python-mongo/tree/pr/471) | [Compare Changes](https://github.com/Azure-Samples/todo-python-mongo/compare/staging...pr/471)

---

2022-08-23 15:33 UTC, merged