update changelog
Azure/azure-dev pull request #527
Opened 2022-08-25 23:01 UTC by hemarina

2022-08-25 23:04 UTC, vhvb1989 approved these changes
I think next release might be the 0.2.0.  But we can update it later

2022-08-26 17:34 UTC, ellismg commented
> I think next release might be the 0.2.0. But we can update it later

If we aren't 100% sure, let's keep it as `0.1.0-beta.6` for now.  We can always go change it to `0.2.0-beta.1` when the terraform stuff lands, but if we change it now going back will be confusing.

2022-08-26 17:36 UTC, ellismg requested changes
We should stay on 0.1.0-beta.6 for now - we can update it once we land some of the more impressive features in the next release.

2022-08-26 17:36 UTC, ellismg commented on cli/version.txt
> +0.2.0-beta.1
I would keep this at `0.1.0-beta.6` until we are certain we are going to rev the minor version number (e.g. after the terraform or azdo changes land)

2022-08-26 17:55 UTC, azure-sdk commented
<!-- #comment-cli-pr -->
## Azure Dev CLI Install Instructions

### Install scripts

#### MacOS/Linux

> May elevate using `sudo` on some platforms and configurations

bash:
```
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527 --version '' --verbose
```

pwsh:
```
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/uninstall-azd.ps1' -OutFile uninstall-azd.ps1; ./uninstall-azd.ps1
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/install-azd.ps1' -OutFile install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527' -Version '' -Verbose
```


#### Windows
```
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/uninstall-azd.ps1' > uninstall-azd.ps1; ./uninstall-azd.ps1;"
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/install-azd.ps1' > install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527' -Version '' -Verbose;"
```

### Standalone Binary

* Linux - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/azd-linux-amd64.tar.gz
* MacOS - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/azd-darwin-amd64.zip
* Windows - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/azd-windows-amd64.zip

### Container
```
docker run -it azdevcliextacr.azurecr.io/azure-dev:pr-527
```

2022-08-26 20:47 UTC, azure-sdk commented
<!-- #comment-cli-pr -->
## Azure Dev CLI Install Instructions

### Install scripts

#### MacOS/Linux

> May elevate using `sudo` on some platforms and configurations

bash:
```
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527 --version '' --verbose
```

pwsh:
```
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/uninstall-azd.ps1' -OutFile uninstall-azd.ps1; ./uninstall-azd.ps1
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/install-azd.ps1' -OutFile install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527' -Version '' -Verbose
```


#### Windows
```
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/uninstall-azd.ps1' > uninstall-azd.ps1; ./uninstall-azd.ps1;"
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/install-azd.ps1' > install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527' -Version '' -Verbose;"
```

### Standalone Binary

* Linux - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/azd-linux-amd64.tar.gz
* MacOS - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/azd-darwin-amd64.zip
* Windows - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/527/azd-windows-amd64.zip

### Container
```
docker run -it azdevcliextacr.azurecr.io/azure-dev:pr-527
```

2022-08-26 22:04 UTC, ellismg approved these changes
LGTM

2022-08-26 22:04 UTC, merged