Fixes provisioning output for container app deployments
Azure/azure-dev pull request #549
Opened 2022-08-29 22:26 UTC by wbreza

Since container app deployments today use a resource group scoped Bicep deployment the output required some updates to correctly display the effected resources.

- [x] Updates resource manager to leverage `infra.Scope`
- [x] Adds support in `infra.Scope` for both subscription level and resource group deployments
- [x] Moves `Scope` from `provisioning` package to `infra` package.

2022-08-29 22:48 UTC, azure-sdk commented
<!-- #comment-cli-pr -->
## Azure Dev CLI Install Instructions

### Install scripts

#### MacOS/Linux

> May elevate using `sudo` on some platforms and configurations

bash:
```
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549 --version '' --verbose
```

pwsh:
```
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/uninstall-azd.ps1' -OutFile uninstall-azd.ps1; ./uninstall-azd.ps1
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/install-azd.ps1' -OutFile install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549' -Version '' -Verbose
```


#### Windows
```
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/uninstall-azd.ps1' > uninstall-azd.ps1; ./uninstall-azd.ps1;"
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/install-azd.ps1' > install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549' -Version '' -Verbose;"
```

### Standalone Binary

* Linux - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/azd-linux-amd64.tar.gz
* MacOS - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/azd-darwin-amd64.zip
* Windows - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/azd-windows-amd64.zip

### Container
```
docker run -it azdevcliextacr.azurecr.io/azure-dev:pr-549
```

2022-08-29 23:15 UTC, azure-sdk commented
<!-- #comment-cli-pr -->
## Azure Dev CLI Install Instructions

### Install scripts

#### MacOS/Linux

> May elevate using `sudo` on some platforms and configurations

bash:
```
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549 --version '' --verbose
```

pwsh:
```
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/uninstall-azd.ps1' -OutFile uninstall-azd.ps1; ./uninstall-azd.ps1
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/install-azd.ps1' -OutFile install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549' -Version '' -Verbose
```


#### Windows
```
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/uninstall-azd.ps1' > uninstall-azd.ps1; ./uninstall-azd.ps1;"
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/install-azd.ps1' > install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549' -Version '' -Verbose;"
```

### Standalone Binary

* Linux - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/azd-linux-amd64.tar.gz
* MacOS - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/azd-darwin-amd64.zip
* Windows - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/azd-windows-amd64.zip

### Container
```
docker run -it azdevcliextacr.azurecr.io/azure-dev:pr-549
```

2022-08-29 23:55 UTC, weikanglim commented on cli/azd/pkg/project/service_target_containerapp.go
> +	infraManager, err := provisioning.NewManager(ctx, *at.env, at.config.Project.Path, at.config.Infra, true)
This hardcoded value makes me wonder if the `interactive` options isn't passed correctly, or that provisioning manager shouldn't know about interactivity if it's meant to be used in this way..

2022-08-29 23:58 UTC, weikanglim commented on cli/azd/pkg/infra/provisioning/provisioning_progress_display.go
> +func (display *ProvisioningProgressDisplay) ReportProgress(ctx context.Context, scope infra.Scope) (*DeployProgress, error) {
Does `scope` still need to be passed to `ReportProgress` if it's also part stored in the struct? I think the lifetime should be with the object (at least the way it was written initially)

2022-08-30 00:03 UTC, weikanglim commented on cli/azd/pkg/infra/azure_resource_manager.go
> +	}
Is this addressing a new issue that occurs with resource group scopes? Is it better to have explicit conditional handling based on the type of scope? For example, if scope is resource group scope, I think the resource group name would be provided directly by the scope.

The fallback seems a little unintuitive unless we can codify in comments how it applies to the general case.

2022-08-30 00:04 UTC, weikanglim commented on cli/azd/pkg/infra/azure_resource_manager.go
> +	}
I think this is similarly unclear why it exists. I suspect it is related to handling resource group scopes vs. subscription scopes and I wonder if we should make it part of an explicit scope-type handling

2022-08-30 00:05 UTC, weikanglim requested changes
Everything looks good... Just want a quick discussion on the `GetDeploymentResourceOperations` handling before final approval.

2022-08-30 17:33 UTC, wbreza commented
> Everything looks good... Just want a quick discussion on the `GetDeploymentResourceOperations` handling before final approval.

Thanks for the great feedback @weikanglim.  Everything should now be addressed.

2022-08-30 17:39 UTC, weikanglim approved these changes
Thanks for addressing all the comments. Looks good to me!

2022-08-30 19:55 UTC, azure-sdk commented
<!-- #comment-cli-pr -->
## Azure Dev CLI Install Instructions

### Install scripts

#### MacOS/Linux

> May elevate using `sudo` on some platforms and configurations

bash:
```
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549 --version '' --verbose
```

pwsh:
```
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/uninstall-azd.ps1' -OutFile uninstall-azd.ps1; ./uninstall-azd.ps1
Invoke-RestMethod 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/install-azd.ps1' -OutFile install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549' -Version '' -Verbose
```


#### Windows
```
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/uninstall-azd.ps1' > uninstall-azd.ps1; ./uninstall-azd.ps1;"
powershell -c "Set-ExecutionPolicy Bypass Process; irm 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/install-azd.ps1' > install-azd.ps1; ./install-azd.ps1 -BaseUrl 'https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549' -Version '' -Verbose;"
```

### Standalone Binary

* Linux - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/azd-linux-amd64.tar.gz
* MacOS - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/azd-darwin-amd64.zip
* Windows - https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/549/azd-windows-amd64.zip

### Container
```
docker run -it azdevcliextacr.azurecr.io/azure-dev:pr-549
```

2022-08-30 21:01 UTC, merged