Change log, pager response, avoid pipeline duplicate
Azure/azure-dev pull request #757
Opened 2022-09-27 20:54 UTC by vhvb1989

2022-09-27 21:02 UTC, hattan requested changes
Thanks for adding this. This is a good pattern to use with the azdo api.

2022-09-27 21:06 UTC, vhvb1989 commented on cli/azd/pkg/azdo/pipeline.go
> +		return nil, fmt.Errorf("creating pipeline: validate name: %s", err)
done

2022-09-27 23:24 UTC, ellismg approved these changes
LGTM

2022-09-28 01:39 UTC, vhvb1989 commented
/check-enforcer override

2022-09-28 01:40 UTC, merged